---
# location and name of todo.txt
TODO:
  PATH: "C:/.../Folder"  # enter target folder 
  FILE: "todo_test.txt"  # todo.txt file name
# location and name of todo.txt archive
# when PATH is empty TODO.PATH will be used  
ARCHIVE: 
  PATH: "C:/.../Folder"
  FILE: "todo_done_test.txt"
# location and name of todo.txt back up files
# when PATH is empty TODO.PATH will be used
BACKUP: 
  PATH: "C:/.../Folder"
  FILE: "todo_backup.bak"
  ARCHIVE: "archive_backup.bak"
# default settings 
SETTINGS:
  SHOW_INFO: false # display verbose information
  COLOR_MAP: TODO_COLORS_BG_WHITE # must match to one of the TODO_COLORS_... profiles
  DATE_CHANGED: true # add changed_date attribute
# color code table see 
# Repo: tools_console > console_utils.py
# https://stackoverflow.com/questions/287871/how-do-i-print-colored-text-to-the-terminal
COLORS:
  COLOR_DICT:
    COLOR_DEFAULT: "1;37;47"
    COLOR_DEFAULT_BG: "1;37;47"
    COLOR_GREY: "1;30;40"
    COLOR_RED: "1;31;40"
    COLOR_GREEN: "1;32;40"
    COLOR_YELLOW: "1;33;40"
    COLOR_BLUE: "1;34;40"
    COLOR_PURPLE: "1;35;40"
    COLOR_LIGHTBLUE: "1;36;40"
    COLOR_WHITE: "1;37;40"
    COLOR_RED_BG: "1;31;41"
    COLOR_GREEN_BG: "1;37;42"
    COLOR_YELLOW_BG: "1;37;43"
    COLOR_BLUE_BG: "1;37;44"
    COLOR_PURPLE_BG: "1;37;45"
    COLOR_LIGHTBLUE_BG: "1;37;46"
    COLOR_WHITE_BG: "1;37;47"
    COLOR_GREY_WH: "1;30;47"
    COLOR_RED_WH: "1;31;47"
    COLOR_GREEN_WH: "1;32;47"
    COLOR_YELLOW_WH: "1;33;47"
    COLOR_BLUE_WH: "1;34;47"
    COLOR_PURPLE_WH: "1;35;47"
    COLOR_LIGHTBLUE_WH: "1;36;47"
    COLOR_BLACK_WH: "1;30;47"
  # customize the task colors refer to one of the values in COLOR_LIST      
  # TODO COLORS DEFAULT      
  TODO_COLORS_DEFAULT:
    DEFAULT_COLOR: COLOR_DEFAULT
    COMPLETE: COLOR_GREEN
    PRIO: COLOR_PURPLE
    DATE_COMPLETED: COLOR_GREEN
    DATE_CREATED: COLOR_LIGHTBLUE
    DESCRIPTION: COLOR_DEFAULT
    LINKS: COLOR_LIGHTBLUE
    PROJECTS: COLOR_PURPLE
    CONTEXTS: COLOR_YELLOW
    ATTRIBUTES: COLOR_YELLOW
    DATE_CHANGED: COLOR_YELLOW
    HASH: COLOR_LIGHTBLUE
    ORIGINAL: COLOR_GREY  
  # TODO COLORS WHITE BACKGROUND
  TODO_COLORS_BG_WHITE:  
    DEFAULT_COLOR: COLOR_DEFAULT_WH
    COMPLETE: COLOR_GREEN_WH
    PRIO: COLOR_PURPLE_WH
    DATE_COMPLETED: COLOR_GREEN_WH
    DATE_CREATED: COLOR_LIGHTBLUE_WH
    DESCRIPTION: COLOR_DEFAULT_WH
    LINKS: COLOR_LIGHTBLUE_WH
    PROJECTS: COLOR_PURPLE_WH
    CONTEXTS: COLOR_YELLOW_WH
    ATTRIBUTES: COLOR_YELLOW_WH
    DATE_CHANGED: COLOR_YELLOW_WH
    HASH: COLOR_LIGHTBLUE_WH
    ORIGINAL: COLOR_GREY_WH  
  # TODO COLORS BLACK BACKGROUND
  TODO_COLORS_BG_BLACK:
    DEFAULT_COLOR: COLOR_DEFAULT_BG
    COMPLETE: COLOR_GREEN_BG
    PRIO: COLOR_PURPLE_BG
    DATE_COMPLETED: COLOR_GREEN_BG
    DATE_CREATED: COLOR_LIGHTBLUE_BG
    DESCRIPTION: COLOR_DEFAULT_BG
    LINKS: COLOR_LIGHTBLUE_BG
    PROJECTS: COLOR_PURPLE_BG
    CONTEXTS: COLOR_YELLOW_BG
    ATTRIBUTES: COLOR_YELLOW_BG
    DATE_CHANGED: COLOR_YELLOW_BG
    HASH: COLOR_LIGHTBLUE_BG
    ORIGINAL: COLOR_DEFAULT_BG
# FIELDS ALOWED FOR FILTERS (SEE BELOW)
PROPERTIES:
  - PROPERTY_COMPLETE          # Task is complete
  - PROPERTY_PRIORITY          # Priority
  - PROPERTY_DATE_CREATED      # Creation Date (datetime)
  - PROPERTY_DATE_CHANGED      # Change Date  (YYYY-MM-DD)
  - PROPERTY_DATE_COMPLETED    # Completion Date (datetime)
  - PROPERTY_DESCRIPTION       # Task description
  - PROPERTY_PROJECTS          # Project List
  - PROPERTY_CONTEXTS          # Context List
  - PROPERTY_ATTRIBUTES        # Attribute List (key:value pairs)
  - PROPERTY_HASH              # Task Hash Value 
  - PROPERTY_CHANGED           # Changed (original<>new) (bool)
  - PROPERTY_ORIGINAL          # Original Todo Task string 
  - PROPERTY_NEW               # New Task String (after amendment)
  - PROPERTY_INDEX             # Index number in Todo list 
  - PROPERTY_ORIGIN            # Origin of Task (ARCHIVE or TODO)
FILTER:
  FILTER_LIST:                 # Single Filter Rules 
    FILTER_PRIO_A_C:           # example for a regex filter
      REGEX: '[A-C]'           # regex, note that no single quotes are used (otherwise messed up)
      INCLUDE: True            # default is true, use false to exclude positive fiter result
      PROPERTY: PROPERTY_PRIORITY
      INFO: "Filter: Priorities A-C" # optional: description       
    FILTER_COMPLETED_LAST_2WEEKS:  # example for a date filter
      DATE_FROM: "TODAY-14"        # date from 14 day<s ago
      DATE_TO: "TODAY+2"            # today
      PROPERTY: PROPERTY_DATE_COMPLETED  # check for dates in field date_completed
    FILTER_COMPLETED:  # example for a booleanfilter
      VALUE: True
      PROPERTY: PROPERTY_COMPLETE
    FILTER_NO_PROPERTY:  # example for a booleanfilter
      VALUE: True
    FILTER_WRONG_FILTER_ATTRIBUTE:  # example for a wrong filter attribute 
      HUGO: WRONG_FILE_ATTRIBUTE_HUGO      
    FILTER_WRONG_PROPERTY:  # example for a wrong property
      PROPERTY: PROPERTY_WRONG
  FILTER_SETS:                 # Filter Sets, will be used to filter using list of defined filters 
    FILTER_WRONG:              # example filter all tasks prio A-C completed last two weeks
      - FILTER_COMPLETEDX      # check that this filter set wil not be used 
      - FILTER_COMPLETED_LAST_2WEEKS
    FILTER_SETCOMPLETED_LAST_2WEEKS: # example filter all tasks prio A-C completed last two weeks
      - FILTER_COMPLETED
      - FILTER_COMPLETED_LAST_2WEEKS
