# sample param_config rename to param_config.yaml and set the
# configpath.py pointing to file location of this file
# sample block for executables
# the parentheses my help to omit invalid optional command paramas
# (for example dropping opening at line commands when no line is submitted)
# you may need to adjust the sample to real files / paths on your computer
# check out all locations with the marker word #REPLACE#
pattern:
  notepadpp:
    pattern: "{[notepadpp]} {[file]} {-n[line]} {[extra]}"
    param:
      notepadpp:
        type: executable # use to check
        help: "Path to notepad++.exe"
      file:
        type: file
        help: "File to be opened"
      line:
        type: param
        help: "File to be opened at line number"
      extra:
        type: param
        help: "Additional params (in quotes) to be appended to command"        
    help: "Opens Notepad++: [notepadpp] -n[line] [extra]"

  vscode:
    pattern: "{[vscode]} {[file]}"
    param:
      vscode:
        type: executable # use to check
        help: "Executable Path"
      file:
        type: file
        help: "File to be opened"
    help: "Opens VSCODE: [vscode] [file]"
  vscode_diff:
    pattern: "{[vscode]} --diff {[oldfile]} {[newfile]}"
    param:
      vscode:
        type: executable # use to check
        help: "Executable Path"
      a_file:
        type: file # can be used to validate
        reference: absolute_file_path
      just_param:
        type: param # just a param without validation
      a_ref_path:
        type: path # can be used to validate
        path: environment_win
        reference: howto
      a_file_path:
        type: path # can be used to validate
        file:
        path: environment_win
        reference: howto
      newfile:
        type: file
        path: path
        reference: folder_in_environment # get the resolved ...
    help: "Performs diff in Visual Codes: [vscode] [oldfile] [newfile]"
# plain definition of executable and where to find it
executable:
  notepadpp:
    file: "notepad++.exe"
    path: "C:/#REPLACE#/Notepad++"
    help: "Path to Notepad++"  
  vscode:
    file: "Code.exe"
    path: "C:/#REPLACE#/VSCode"
    help: "Path to VS Code"
  cygwin:
    file: "xyz"
    help: "short help text goes here"
# sample block for folder paths (reusable)
path:
  # example for reference to be looked in environment_win section
  folder_in_environment:
    path: environment_win # this points to environment_win
    reference: howto      # this points to howto config
    help: "xdrf"
  work_folder:
    path: "path>work_folder"
    help: "xdrf"
  favorites_folder:
    path: "C:/#REPLACE#"
    help: "xdrf"
  wrong_folder:
    help: "xdrf"
# sample block for document paths
file:
  absolute_file_path:
    file: "C:/#REPLACE#/testfile.txt"
    help: "sample for an absolute file"
  file_name_and_path:
    file: "testfile.txt"
    path: "C:/#REPLACE#"
    help: "sample for an absolute fiöe"
  file_name_and_ext_path:
    file: "test.png"
    path: environment_win
    reference: valid_path # use reference to point to ref field
    help: "sample for an absolute fiöe"
  file_name_ext_path_only:
    file: environment_win
    path: environment_win
    reference: valid_file
    help: "sample for an absolute fiöe"
  xyz: # testing resolve_params
    file: "C:/#REPLACE#/param_config.yaml"
    help: "sample for a referenced file"    

# sample block for scripts
script_win:
  bat1:
    file: "xyz"
    path: "xyz path"
    help: "short help text goes here"
# sample block for scripts bash
script_bash:
  bat1:
    file: "xyz"
    help: "short help text goes here"
# sample block for environment variables for win cmd
environment_win:
  folder_in_environment: # referenced in path
    value: "xyz"
    path: "C:/#REPLACE#"
    help: "description"
  howto:
    value: "xyz"
    path: "C:/"
    export: path # use export which attribute is to be exported as script
    help: "description"
  valid_path:
    value: "xyz"
    path: "C:/#REPLACE#"
    help: "description"
  valid_file:
    value: "xyz"
    file: "C:/#REPLACE#test.png"
    help: "description"
  howto2:
    value: "xyz"
    file: "xyz"
    path: "optional"
    help: "description"
# sample block for environment variables for win cmd
environment_bash:
  howto:
    value: "xyz"
    path: "optional"
    help: "description"
  howto2:
    value: "xyz"
    file: "xyz"
    path: "optional"
    help: "description"
# sample block for command line shortcuts:
# refers to elements in
# scripts, executables, documents section above
shortcut:
  cygwin:
    file: cygwin.exe
    path: sdsd
    help: "Display Path: -d -a [<filename>]/-p <.|path>"
  bat1:
    file: bat1
    help: "Display Path: -d -a [<filename>]/-p <.|path>"
  my_doc:
    file: howto
    help: "this is my knowledge collection"

# SAMPLE BLOCK for INPUT PARAMS USED FOR COMMAND LINE
cmd_param:
  # command line options for notepad++
  cmdparam_notepadpp:
    help: "Notepad++ Command Line Input"
    file:
      param_short: f
      param: file
      default: null
      help: "File to be opened"
      metavar: "[file]"
    line:
      param_short: l
      param: line
      default: null
      help: "Open File at submitted Line"
      metavar: "[line]"
    extra:
      param_short: x
      param: extra
      default: null
      help: "Extra parameters, will be appended to command"
      metavar: "[..extra params..]"
  # default params to be used frequently
  cmdparam_default:
    help: "often used default parameters"
    file:
      param_short: f
      param: file
      default: null
      help: "Input File"
      metavar: "[file]"
    file_out:
      param_short: fo
      param: file_out
      default: null
      help: "Output File"
      metavar: "[file_out]"
    csv_separator:
      param_short: csep
      param: csv_sep
      default: ";"
      help: "CSV separator, default is ';'"
      metavar: "[;]"
    decimal_separator:
      param_short: dsep
      param: dec_sep
      default: ","
      help: "decimal spearator, default is ','"
      metavar: "[,]"
    loglevel:
      param_short: ll
      param: loglevel
      default: info
      choices: ["debug","info","warning","error"]
      help: "Set loglevel (debug,info,warning,error)"
      metavar: "[loglevel]"
    add_timestamp:
      param_short: ts
      param: add_timestamp
      dest: add_timestamp
      action: "store_true"
      help: "Help Comment True"

  # main params template
  cmd_client_main:
    help: "Main parameters for the cmd_client"  
    sample_main_param:
      param_short: ps
      param: param_short
      default: null
      help: "Help Comment"
      metavar: "[param_short]"    

  # parameters to be used as copy paste templates
  cmdparam_template:
    help: "description of the cmdparams template"
    # sample block for param input
    sample_param:
      param_short: ps
      param: param_short
      default: null
      help: "Help Comment"
      metavar: "[param_short]"
    # sample block for true boolean
    sample_bool_true:
      param_short: sbt
      param: sbtrue
      dest: sbtrue
      action: "store_true"
      help: "Help Comment True"
    # sample block for false boolean
    sample_bool_false:
      param_short: sbf
      param: sbfalse
      dest: sbfalse
      action: "store_false"
      help: "Help Comment False"
# subparser structures
cmd_subparser:
  # this is the subparser config name
  subparser_sample_config:
    # the keys correspond to the first subparam,
    # (which will be used as (sub)command)
    # values must match the cmdparams key
    # if there is a help in the params template it will be used
    subparse_cmd: cmdparam_template
  subparser_cmd_client:
    npp: cmdparam_notepadpp
# mapping command line items to configuration items
# the key should be the same 
# if nothing is mapped by default a resolved value will be 
# aadded as an additional field to the cmd configuration
# default case should be a mapping to a pattern 
cmd_map:
  cmdparam_notepadpp:  # mapping cmdparam_notepadpp params to a pattern
    help: "Map Config Items to command pattern"
    map: 
      type: pattern                 # this is the rule for how to map
      cmd_param: cmdparam_notepadpp # maps the command line params ..
      pattern: notepadpp            # .. to a specific pattern






